//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hfs.Web.RestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Emails = new HashSet<Email>();
            this.LegalNames = new HashSet<LegalName>();
            this.Phones = new HashSet<Phone>();
            this.Groups = new HashSet<Group>();
        }
    
        public int account_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string username { get; set; }
        public int pbkdf2_iterations { get; set; }
        public byte[] password_salt { get; set; }
        public byte[] password_hash { get; set; }
        public System.DateTime created_dt { get; set; }
    
        public virtual ICollection<Email> Emails { get; set; }
        public virtual ICollection<LegalName> LegalNames { get; set; }
        public virtual ICollection<Phone> Phones { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
    }
}
