//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hfs.Web.RestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int email_id { get; set; }
        public int account { get; set; }
        public string address { get; set; }
        public bool is_primary { get; set; }
        public Nullable<System.DateTime> verify_dt { get; set; }
    
        public virtual Account Account1 { get; set; }
    }
}
