//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hfs.Web.RestApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HFSDBEntities : DbContext
    {
        public HFSDBEntities()
            : base("name=HFSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<LegalName> LegalNames { get; set; }
        public virtual DbSet<NameSuffix> NameSuffixes { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Phone> Phones { get; set; }
        public virtual DbSet<PhoneBlacklist> PhoneBlacklists { get; set; }
        public virtual DbSet<PhoneRegion> PhoneRegions { get; set; }
        public virtual DbSet<PhoneType> PhoneTypes { get; set; }
        public virtual DbSet<VerificationCode> VerificationCodes { get; set; }
    }
}
