//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hfs.Web.RestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NameSuffix
    {
        public NameSuffix()
        {
            this.LegalNames = new HashSet<LegalName>();
        }
    
        public int name_suffix_id { get; set; }
        public string name_suffix { get; set; }
    
        public virtual ICollection<LegalName> LegalNames { get; set; }
    }
}
