//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hfs.Web.RestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneBlacklist
    {
        public int phone_blacklist_id { get; set; }
        public string phone_number { get; set; }
        public string method { get; set; }
        public System.DateTime added_dt { get; set; }
    }
}
